name: Update production version

on:
  pull_request:
    branches:
      - main
      - master
      - test/workflows

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization

