name: Build docker application

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      package_json_paths:
        type: string
        required: false
      dot_net_file_path:
        type: string
        required: false
      registry:
        required: true
        type: string
      with_args:
        required: true
        type: boolean
      dockerfile_path:
        required: true
        type: string
    secrets:
      token:
        required: true
    outputs:
      repo_name:
        value: ${{ jobs.Build_app.outputs.repo_name }}

jobs:
  Update_app_version:
    uses: ./.github/workflows/release_new_version.yml
    with:
      package_json_paths: ${{ inputs.package_json_paths }}
      dot_net_file_path: ${{ inputs.dot_net_file_path }}
    secrets:
      ci_token: ${{ secrets.token }}
      
  Build_app:
    needs: Update_app_version
    uses: ./.github/workflows/build_push_docker_image.yml
    with:
      registry: ${{ inputs.registry }}
      with_args: ${{ inputs.with_args }}
      dockerfile_path: ${{ inputs.dockerfile_path }}
    secrets:
      token: ${{ secrets.token }}