name: Build and publish dotnet application

on:
  workflow_call:
    inputs:
      file_with_version:
        required: true
        type: string
      dot_net_version:
        required: true
        type: string
      csproj_path:
        required: true
        type: string
      build_file:
        required: true
        type: string
      package_name:
        required: true
        type: string
    secrets:
      ci_token:
        required: true

jobs:
  Get_version:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/get_version_number.yml
    secrets:
      token: ${{ secrets.ci_token }}

  Build_and_publish:
    needs: Get_version
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ci_token }}

      - name: Setup .NET ${{ inputs.dot_net_version }}.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '${{ inputs.dot_net_version }}.x'

      - name: Update .net file version
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.6
        with:
          file: "${{ inputs.file_with_version }}"
          version: ${{ needs.Get_version.outputs.new_version }}

      - name: Create a GitHub release
        if: ${{ github.base_ref == github.event.repository.default_branch }}
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ needs.Get_version.outputs.new_v-version }}"
          makeLatest: ${{ github.base_ref == github.event.repository.default_branch }}

      - name: Package the project
        run: |
          dotnet pack ${{ inputs.csproj_path }}/${{ inputs.build_file }} -p:PackageID=${{ inputs.package_name }} -p:Version=${{ needs.Get_version.outputs.new_version }} --configuration Release

      - name: Publish the package
        run: |
          dotnet nuget push "${{ inputs.csproj_path }}/bin/Release/${{ inputs.package_name }}.${{ needs.Get_version.outputs.new_version }}.nupkg"  --api-key ${{ secrets.ci_token }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}"
