name: Reusable workflwo for updating production version

on:
  workflow_call:
    secrets:
      ci_token:
        required: true

jobs:
  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          token: ${{ secrets.ci_token }}

      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version.outputs.current-v-version }}"
