name: Deploy application to server

on:
  workflow_call:
    inputs:
      host:
        type: string
        required: true
      scp_files:
        type: string
        required: true
      scp_files_target_location:
        type: string
        required: true
      registry:
        required: true
        type: string
      compose_file_location:
        required: true
        type: string
    secrets:
      token:
        required: true
      key:
        required: true
      passphrase:
        required: true
    outputs:
      repo_name:
        value: ${{ jobs.Deploy.outputs.repo_name }}
      tags:
        value: ${{ jobs.Deploy.outputs.tags }}

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    outputs: 
      repo_name: ${{ steps.repo_name.outputs.lowercase }}
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - id: repo_name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.event.repository.name }}

      - id: username
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.actor }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ inputs.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: copy docker compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ inputs.host }}
          key: ${{ secrets.key }}
          passphrase: ${{ secrets.passphrase }}
          port: 22
          source: ${{ inputs.scp_files }}
          target: ${{ inputs.scp_files_target_location }}
          overwrite: true
