name: Update production version in package.json file

on:
  workflow_call:
    inputs:
      be_folder:
        type: string
        required: false
      fe_folder:
        type: string
        required: false
      version:
        type: string
        required: true

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Update backend/package.json Version
        if: inputs.be_folder != ''
        run: |
          jq ".version=\"${{ inputs.version }}\"" ${{ inputs.be_folder }}/package.json > ${{ inputs.be_folder }}/temp.json && mv ${{ inputs.be_folder }}/temp.json ${{ inputs.be_folder }}/package.json

      - name: Update frontend/package.json Version
        if: inputs.fe_folder != ''
        run: |
          jq ".version=\"${{ inputs.version }}\""  ${{ inputs.fe_folder }}/package.json > ${{ inputs.fe_folder }}/temp.json && mv ${{ inputs.fe_folder }}/temp.json ${{ inputs.fe_folder }}/package.json