name: Reusable workflwo for updating production version

on:
  workflow_call:
    # inputs:
    #   application:
    #     type: string
    #     required: true
    #   change:
    #       type: string
    #       required: true


jobs:
  extract_pr_body:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract PR body
      id: extract_pr_body
      run: echo "${{ github.event.pull_request.body }}" > pr_body.txt

    - name: Extract Change Type
      id: extract_change_type
      run: |
        type_of_change=$(grep -oP '(?<=<!-- Note: The selected type of change will affect the semantic version of the app. -->\n- \[.\] (Major|Minor|Patch|No Version Change))' pr_body.txt)
        type_of_change=${type_of_change//\[\]/}
        type_of_change=$(echo $type_of_change | xargs)
        echo "TYPE_OF_CHANGE=$type_of_change" >> $GITHUB_ENV

    - name: Output Change Type
      run: |
         echo "The selected type of change is: ${{ env.TYPE_OF_CHANGE }}"