name: Reusable workflwo for updating production version

on:
  workflow_call:
    # inputs:
    #   application:
    #     type: string
    #     required: true
    #   change:
    #       type: string
    #       required: true


jobs:
  extract_pr_body:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract PR body
      id: extract_pr_body
      run: echo "${{ github.event.pull_request.body }}" > pr_body.txt

    - name: Print PR body
      run: |
        cat pr_body.txt

    - name: Extract Change Type
      id: extract_change_type
      run: |
        CHANGE_TYPE=$(grep -Eo '\[x\] (Major|Minor|Patch|No Version Change)' pr_body.txt | sed -E 's/\[x\] //')
        echo "change_type=$CHANGE_TYPE" >> $GITHUB_ENV

    # - name: Extract Change Type
    #   id: extract_change_type
    #   run: |
    #     change_type=$(grep -oP '- \[x\] (Major|Minor|Patch|No Version Change)' pr_body.txt | head -n 1)
    #     change_type=${change_type#'- [x] '}
    #     echo "TYPE_OF_CHANGE=$change_type" >> $GITHUB_ENV

    - name: Output Change Type
      run: |
        echo "The selected type of change is: ${{ env.TYPE_OF_CHANGE }}"