name: Reusable workflwo for updating production version

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      node_be_folder_path:
        type: string
        required: false
      node_fe_folder_path:
        type: string
        required: false
      dot_net_file_path:
        type: string
        required: false
    secrets:
      workflow_bot_token:
        required: true

jobs:
  Get_prod_version:
    uses: ./.github/workflows/get_production_version.yml

  Update_version_in_code:
    needs: Get_prod_version
    runs-on: ubuntu-latest
    if: needs.Get_prod_version.outputs.new_prod_version.value != ''
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_BOT_ID }}
          private-key: ${{ secrets.workflow_bot_token }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Update package json
        if: inputs.node_be_folder_path != '' || inputs.node_fe_folder_path != '' 
        uses: ./.github/workflows/update_package_json.yml
        with:
          be_folder: ${{ inputs.node_be_folder_path }}
          fe_folder: ${{ inputs.node_fe_folder_path }}
          version: ${{ needs.Get_prod_version.outputs.new_prod_version }}

      - name: Set MyProject.csproj version
        if: inputs.dot_net_file_path != ''
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.6
        with:
          file: "${{ inputs.dot_net_file_path }}"
          version: ${{  needs.Get_prod_version.outputs.new_prod_version.value }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Changed application version in package.json to ${{  needs.Get_prod_version.outputs.new_prod_version.value }}"
          committer_name: Nittin GitHub Actions
          committer_email: actions@nittin.cz
          tag: ${{ needs.Get_prod_version.outputs.new_prod_version.value }}
          github_token: ${{ steps.app-token.outputs.token }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{  needs.Get_prod_version.outputs.new_prod_version.value }}"
